import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { z } from 'zod';

import {
  buildHeader,
  compileTex,
  escapeLatex,
  escapePdfString,
  headerSchema,
  LANGUAGE_BABEL,
  parseOrRefuse,
  slugify,
} from './document.ts';

/**
 * The cover letter's render pipeline — the résumé's sibling. The model emits a
 * Letter as structured data and a fixed template renders it, exactly as for a
 * Selection ([ADR-0004](../../../docs/adr/0004-structured-selection-with-a-fixed-template.md)),
 * so the two documents share one identity header and read as a pair.
 *
 * A letter differs from a résumé in one way that matters: it has to say why
 * Daniel wants *this* job, and his motives are not in the Corpus. The schema makes
 * that explicit ([ADR-0010](../../../docs/adr/0010-a-cover-letter-says-only-what-daniel-said.md)):
 * every paragraph cites where its claims come from, and a paragraph citing
 * `daniel` is refused unless the Letter carries Daniel's own words in `statedByDaniel`.
 */

/** The template version. A Letter must declare the same number. */
export const LETTER_VERSION = 1;

/**
 * The sources a paragraph may cite besides an Accomplishment id:
 *
 * - `posting` — a restatement of what the employer's own posting says.
 * - `identity` — `content/identity.md` (who Daniel is, how he works, availability).
 * - `daniel` — something Daniel said in the session, recorded in `statedByDaniel`.
 *
 * Anything else must be the id of a `content/accomplishments/*.md` file; the CLI
 * checks that, as it does for a Selection.
 */
export const LETTER_NON_CORPUS_SOURCES = ['posting', 'identity', 'daniel'] as const;

/**
 * One paragraph of the letter body. `sources` is the audit trail, never printed:
 * it lets a reviewer check each paragraph against what it claims to draw on.
 */
const paragraphSchema = z.strictObject({
  text: z.string().min(1),
  sources: z.array(z.string().min(1)).min(1),
});

/** Who the letter is addressed to. Only the organisation is required. */
const recipientSchema = z.strictObject({
  organisation: z.string().min(1),
  name: z.string().min(1).optional(),
  location: z.string().min(1).optional(),
});

/**
 * The whole contract between the model and the letter template. Strict
 * throughout, like the Selection. Two to five paragraphs: fewer is a note, more
 * no longer fits the page a reader will give it.
 */
export const letterSchema = z
  .strictObject({
    version: z.literal(LETTER_VERSION),
    language: z.enum(['en', 'pt']).default('en'),
    targetRole: z.string().min(1),
    header: headerSchema,
    recipient: recipientSchema,
    date: z.string().min(1),
    salutation: z.string().min(1),
    paragraphs: z.array(paragraphSchema).min(2).max(5),
    closing: z.string().min(1),
    statedByDaniel: z.array(z.string().min(1)).default([]),
  })
  .refine(
    (letter) =>
      letter.statedByDaniel.length > 0 ||
      letter.paragraphs.every((paragraph) => !paragraph.sources.includes('daniel')),
    {
      message:
        "a paragraph cites 'daniel' but statedByDaniel is empty — record what Daniel said, or drop the claim",
      path: ['statedByDaniel'],
    },
  );

export type Letter = z.infer<typeof letterSchema>;

function parseLetter(input: unknown): Letter {
  return parseOrRefuse(letterSchema, input, 'Letter');
}

/**
 * The preamble. Same fonts and header as the résumé, wider margins and a larger
 * size: a letter is read as prose, not scanned as a list.
 */
function buildPreamble(letter: Letter): string[] {
  const pdfName = escapePdfString(letter.header.name);
  return [
    '% Generated by src/lib/render/letter.ts from a Letter - do not edit by hand.',
    '',
    '\\documentclass[a4paper,11pt]{article}',
    '',
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage[T1]{fontenc}',
    `\\usepackage[${LANGUAGE_BABEL[letter.language]}]{babel}`,
    '\\usepackage{geometry}',
    '\\usepackage{parskip}',
    '\\usepackage{hyperref}',
    '',
    '\\geometry{top=1.5cm, bottom=2.0cm, left=2.2cm, right=2.2cm}',
    '\\pagestyle{empty}',
    '',
    '\\hypersetup{',
    `    pdftitle={Cover letter - ${pdfName}},`,
    `    pdfauthor={${pdfName}},`,
    '    colorlinks=true,',
    '    linkcolor=black,',
    '    urlcolor=black',
    '}',
    '',
  ];
}

/** The recipient block, one line per part, above the date. */
function buildRecipient(letter: Letter): string[] {
  const { recipient } = letter;
  const parts = [recipient.name, recipient.organisation, recipient.location]
    .filter((part): part is string => part !== undefined)
    .map(escapeLatex);
  return [parts.join(' \\\\\n'), ''];
}

function buildTex(letter: Letter): string {
  const lines: string[] = [
    ...buildPreamble(letter),
    '\\begin{document}',
    '',
    ...buildHeader(letter.header),
    '',
    '\\vspace{0.4cm}',
    '',
    ...buildRecipient(letter),
    `\\hfill ${escapeLatex(letter.date)}`,
    '',
    escapeLatex(letter.salutation),
    '',
  ];

  for (const paragraph of letter.paragraphs) {
    lines.push(escapeLatex(paragraph.text), '');
  }

  lines.push(
    escapeLatex(letter.closing),
    '',
    '\\vspace{0.3cm}',
    escapeLatex(letter.header.name),
    '',
    '\\end{document}',
  );
  return `${lines.join('\n')}\n`;
}

/**
 * Render a Letter to a LaTeX document string. Throws `RenderError` if the Letter
 * does not match the schema.
 */
export function renderLetterToTex(input: unknown): string {
  return buildTex(parseLetter(input));
}

/**
 * Render a Letter to a PDF via Tectonic, writing both the `.tex` and the `.pdf`
 * into `outDir`. Validates first, so a malformed Letter fails before any file is
 * written.
 */
export function renderLetterToPdf(
  input: unknown,
  options: { outDir: string; name?: string },
): { texPath: string; pdfPath: string } {
  const letter = parseLetter(input);
  const tex = buildTex(letter);
  const name = options.name ?? slugify(letter.targetRole, 'letter');

  mkdirSync(options.outDir, { recursive: true });
  const texPath = join(options.outDir, `${name}.tex`);
  const pdfPath = join(options.outDir, `${name}.pdf`);
  writeFileSync(texPath, tex, 'utf8');

  compileTex(texPath, options.outDir);
  return { texPath, pdfPath };
}
